### ISSUE TITLE
not working on viaplay.pl

### ISSUE THREAD

**Issue by jikard0** [Mariusz89B/kodi-viaplay#23]
Not working at all on Ubuntu 22.04 kodi 19.4 , i tried v2.4.5 and 2.4.6-beta.3 and it was the same.
Kodi 19.4

Error
2023-09-13 17:31:46.725 T:743152   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SystemError'>
                                                   Error Contents: initialization of md__mypyc did not return an extension module
                                                   Traceback (most recent call last):
                                                     File "/home/user/.kodi/addons/plugin.video.viaplay/default.py", line 2, in <module>
                                                       from resources.lib import addon
                                                     File "/home/user/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 8, in <module>
                                                       from resources.lib.kodihelper import KodiHelper
                                                     File "/home/user/.kodi/addons/plugin.video.viaplay/resources/lib/kodihelper.py", line 5, in <module>
                                                       from .viaplay import Viaplay
                                                     File "/home/user/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 23, in <module>
                                                       import requests
                                                     File "/home/user/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 48, in <module>
                                                       from charset_normalizer import __version__ as charset_normalizer_version
                                                     File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
                                                       from .api import from_bytes, from_fp, from_path
                                                     File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/api.py", line 5, in <module>
                                                       from .cd import (
                                                     File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/cd.py", line 9, in <module>
                                                       from .md import is_suspiciously_successive_range
                                                   SystemError: initialization of md__mypyc did not return an extension module
                                                   -->End of Python script error report<--

**Comment by kedarz** [comment]
I have the same issue with coreelec 20

**Comment by praspp** [comment]
Cześć,
K19.5, ATV 9, plugin.video.viaplay v2.4.6-c7771b0
Wcześniej wtyczka nie wyświetlała zawartości serwisu. Teraz problem z logowaniem.
@Mariusz89B - mógłbyś na to spojrzeć?
Pozdr
@praspp

- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resources.lib.viaplay.Viaplay.ViaplayError'>
                                                   Error Contents: 'MissingSessionCookieError'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 190, in run
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 351, in root
                                                       pages = helper.vp.get_root_page()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 439, in get_root_page
                                                       raise self.ViaplayError('MissingSessionCookieError')  # raise error if user is not logged in
                                                   resources.lib.viaplay.Viaplay.ViaplayError: 'MissingSessionCookieError'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
                                                       addon.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 196, in run
                                                       plugin.run()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 351, in root
                                                       pages = helper.vp.get_root_page()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 439, in get_root_page
                                                       raise self.ViaplayError('MissingSessionCookieError')  # raise error if user is not logged in
                                                   resources.lib.viaplay.Viaplay.ViaplayError: 'MissingSessionCookieError'

-->End of Python script error report<--
2023-09-17 19:34:44.897 T:14415    INFO <general>: Python interpreter stopped
2023-09-17 19:34:44.917 T:14402   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.viaplay/
2023-09-17 19:34:44.935 T:18080   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/) failed

**Comment by praspp** [comment]
> Cześć,
> K19.5, ATV 9, plugin.video.viaplay v2.4.6-c7771b0
> Wcześniej wtyczka nie wyświetlała zawartości serwisu. Teraz problem z logowaniem.
> @Mariusz89B - mógłbyś na to spojrzeć?
> Pozdr
> @praspp
> 
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'resources.lib.viaplay.Viaplay.ViaplayError'>
>                                                    Error Contents: 'MissingSessionCookieError'
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 190, in run
>                                                        plugin.run()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
>                                                        self._dispatch(self.path)
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
>                                                        view_func(**kwargs)
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 351, in root
>                                                        pages = helper.vp.get_root_page()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 439, in get_root_page
>                                                        raise self.ViaplayError('MissingSessionCookieError')  # raise error if user is not logged in
>                                                    resources.lib.viaplay.Viaplay.ViaplayError: 'MissingSessionCookieError'
>                                                    
>                                                    During handling of the above exception, another exception occurred:
>                                                    
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
>                                                        addon.run()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 196, in run
>                                                        plugin.run()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
>                                                        self._dispatch(self.path)
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
>                                                        view_func(**kwargs)
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 351, in root
>                                                        pages = helper.vp.get_root_page()
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.viaplay/resources/lib/viaplay.py", line 439, in get_root_page
>                                                        raise self.ViaplayError('MissingSessionCookieError')  # raise error if user is not logged in
>                                                    resources.lib.viaplay.Viaplay.ViaplayError: 'MissingSessionCookieError'
> 
> -->End of Python script error report<--
> 2023-09-17 19:34:44.897 T:14415    INFO <general>: Python interpreter stopped
> 2023-09-17 19:34:44.917 T:14402   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.viaplay/
> 2023-09-17 19:34:44.935 T:18080   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/) failed
‐---------------------------------------------------------------------
Dzisiaj, tj. 18.09.2023 r. wtyczka ponownie zaczeła działać bez problemu. Mogę się już zlogować, treści są widoczne, odtwarzanie-ok. Przyczyny problemów z dnia 17.09.2023 r. leżały prawdopodobnie po stronie Viaplay.

**Comment by praspp** [comment]
Dzisiaj, tj. 18.09.2023 r. wtyczka ponownie zaczeła działać bez problemu. Mogę się już zlogować, treści są widoczne, odtwarzanie-ok. Przyczyny problemów z dnia 17.09.2023 r. leżały prawdopodobnie po stronie Viaplay.

**Comment by kedarz** [comment]
> I have the same issue with coreelec 20

U mnie tez ponownie dziala
