### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by stnufc** [Mariusz89B/kodi-viaplay#8]
Hi! Thanks so much for continuing supporting this addon for Kodi 18 Leia. Unfortunately, after I installed this addon, I wasnt being able to open it (DK, but I tried with other countries too)... I tried 2.3.2 and 2.3.3 versions. Any fixes? I uninstalled previous version (2.2.2) fully (I wasnt able to enter 'sport' category there, so I found your addon).

Log: 

2022-04-22 11:44:43.473 T:2368   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://mirrors.kodi.tv/addons/leia/plugin.video.snnow/icon.png
2022-04-22 11:44:43.700 T:2368   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://mirrors.kodi.tv/addons/leia/plugin.video.spurs-tv/resources/images/icon.png
2022-04-22 11:45:15.837 T:13008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'translatePath'
                                            Traceback (most recent call last):
                                              File "C:\Users\hhh\AppData\Roaming\Kodi\addons\plugin.video.viaplay\default.py", line 2, in <module>
                                                from resources.lib import addon
                                              File "C:\Users\hhh\AppData\Roaming\Kodi\addons\plugin.video.viaplay\resources\lib\addon.py", line 33, in <module>
                                                profile_path = xbmcvfs.translatePath(xbmcaddon.Addon().getAddonInfo('profile'))
                                            AttributeError: 'module' object has no attribute 'translatePath'
                                            -->End of Python script error report<--
2022-04-22 11:45:15.873 T:16336   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.viaplay/ 
2022-04-22 11:45:15.884 T:10156   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/) failed

**Comment by Mariusz89B** [comment]
@stnufc [stnufc](https://github.com/stnufc) Should be working now.
https://github.com/Mariusz89B/kodi-viaplay/commit/9e17576b86e939f5e6dd9e73016fc5140d50303a

**Comment by stnufc** [comment]
You are hero! Thanks so much! It is indeed fixed! All working fine! Again, thanks for you work!!
